import { NextRequest, NextResponse } from 'next/server';
import { createRoom, getRoom } from '@/lib/db';
import { generateRoomCode, normalizeRoomCode } from '@/lib/roomCodes';

const MAX_ROOM_CODE_ATTEMPTS = 10;

function isDuplicateRoomError(error: unknown) {
  return typeof error === 'object' && error !== null && 'code' in error && error.code === '23505';
}

export async function POST(req: NextRequest) {
  const { roomId, autoGenerated, description } = await req.json().catch(() => ({
    roomId: '',
    autoGenerated: false,
    description: '',
  }));

  const clean = typeof roomId === 'string'
    ? normalizeRoomCode(roomId)
    : '';

  if (clean) {
    const roomDescription = description?.trim() || `Room ${clean}`;

    try {
      const room = await createRoom(clean, roomDescription);
      return NextResponse.json({ room });
    } catch (error) {
      if (isDuplicateRoomError(error)) {
        if (autoGenerated) {
          return createGeneratedRoom(description);
        }

        const room = await getRoom(clean);
        if (room) return NextResponse.json({ room });
      }

      return NextResponse.json({ error: 'Unable to create room' }, { status: 500 });
    }
  }

  return createGeneratedRoom(description);
}

async function createGeneratedRoom(description: unknown) {
  for (let attempt = 0; attempt < MAX_ROOM_CODE_ATTEMPTS; attempt += 1) {
    const generatedRoomId = generateRoomCode();
    const roomDescription = typeof description === 'string' && description.trim()
      ? description.trim()
      : `Room ${generatedRoomId}`;

    try {
      const room = await createRoom(generatedRoomId, roomDescription);
      return NextResponse.json({ room });
    } catch (error) {
      if (isDuplicateRoomError(error)) continue;
      return NextResponse.json({ error: 'Unable to create room' }, { status: 500 });
    }
  }

  return NextResponse.json({ error: 'Unable to generate a unique room code' }, { status: 500 });
}

export async function GET(req: NextRequest) {
  const { searchParams } = new URL(req.url);
  const roomId = searchParams.get('roomId');
  if (!roomId) return NextResponse.json({ error: 'roomId required' }, { status: 400 });
  const clean = normalizeRoomCode(roomId);
  const room = await getRoom(clean);
  if (!room) return NextResponse.json({ error: 'Room not found' }, { status: 404 });
  return NextResponse.json({ room });
}
